#pragma once

class Picture;
class Game;
class SaveDataControl;
class GameScene;
class TitleScene;
class TitleVideoScene;
class StageSelectScene;
class OptionScene;
class CreditScene;
class Player;
class Map;
class Slider;
class ChaseGhost;
class SolarPanel;
class Scene;
class LightCmp;
class RayCast;
class Actor;
class Sound;
class FadeUI;

class RigidbodyCmp;
class MapCollision;
class CollisionManeger;
class PictureManeger;
class SceneManeger;
class ActorManager;
class SoundManager;